/**
 * @file minerva.h
 * @brief Minerva public API
 *
 *  ███╗   ███╗██╗███╗   ██╗███████╗██████╗ ██╗   ██╗ █████╗
 *  ████╗ ████║██║████╗  ██║██╔════╝██╔══██╗██║   ██║██╔══██╗
 *  ██╔████╔██║██║██╔██╗ ██║█████╗  ██████╔╝██║   ██║███████║
 *  ██║╚██╔╝██║██║██║╚██╗██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══██║
 *  ██║ ╚═╝ ██║██║██║ ╚████║███████╗██║  ██║ ╚████╔╝ ██║  ██║
 *  ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚═╝  ╚═╝
 *
 *  Minimal Inference Engine for Robust, Verifiable, and Authenticated ML
 *  Version 1.1.0 — "Athena"
 *
 *  The Three Minerva Laws:
 *    I.   Minerva never produces output from an unverified model.
 *    II.  Minerva reveals nothing through timing, power, or output behavior.
 *    III. Minerva never allocates. Every byte is known at compile time.
 *
 *  USAGE:
 *    1. Edit include/mnv_config.h for your target MCU and model topology.
 *    2. Run: python compiler/minerva_compile.py model.tflite --key key.bin
 *       This emits weights.c and weights.h for your project.
 *    3. In your application:
 *
 *       #include "minerva.h"
 *       #include "weights.h"        // generated by compiler
 *
 *       static mnv_ctx_t ctx;
 *
 *       void setup(void) {
 *           mnv_status_t s = mnv_init(&ctx, &my_model);
 *           if (s != MNV_OK) { handle_error(s); }
 *       }
 *
 *       void loop(void) {
 *           int8_t input[MNV_INPUT_SIZE]   = { ... };
 *           int8_t output[MNV_OUTPUT_SIZE] = { 0 };
 *           mnv_status_t s = mnv_run(&ctx, input, output);
 *           if (s == MNV_OK) { use_output(output); }
 *       }
 */

#ifndef MINERVA_H
#define MINERVA_H

#include "mnv_config.h"
#include "mnv_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 * VERSION
 * ========================================================================= */

#define MNV_VERSION_MAJOR   1
#define MNV_VERSION_MINOR   3
#define MNV_VERSION_PATCH   0
#define MNV_VERSION_STR     "1.3.0-Athena"

/* =========================================================================
 * LIFECYCLE
 * ========================================================================= */

/**
 * @brief Initialize Minerva context.
 *
 * Performs:
 *   1. Context zeroing and canary placement.
 *   2. BLAKE2s integrity check over the encrypted weight blob.
 *   3. ChaCha20 keystream precomputation for layer 0.
 *
 * Must be called before mnv_run(). If this returns anything other than
 * MNV_OK, the device should be treated as compromised.
 *
 * @param ctx    Pointer to a statically allocated mnv_ctx_t.
 * @param model  Pointer to the model descriptor (typically in PROGMEM).
 * @return MNV_OK on success, error code otherwise.
 */
mnv_status_t mnv_init(mnv_ctx_t *ctx, const mnv_model_t *model);

/**
 * @brief Destroy context and zero all sensitive state.
 *
 * Zeroes weight scratch, activation buffers, and ChaCha20 keystream.
 * Call before power-down or context hand-off.
 *
 * @param ctx  Pointer to initialized mnv_ctx_t.
 */
void mnv_destroy(mnv_ctx_t *ctx);

/* =========================================================================
 * INFERENCE
 * ========================================================================= */

/**
 * @brief Run one inference pass.
 *
 * Performs:
 *   1. Canary check (pre-inference).
 *   2. Input validation (constant-time range check).
 *   3. Forward pass with on-the-fly weight decryption.
 *   4. Double-run comparison (if MNV_ENABLE_DOUBLE_RUN).
 *   5. Confidence check.
 *   6. Canary check (post-inference).
 *   7. Weight scratch zeroing.
 *
 * @param ctx     Initialized context.
 * @param input   Q8 input vector of length MNV_INPUT_SIZE.
 * @param output  Q8 output vector of length MNV_OUTPUT_SIZE. Zeroed on error.
 * @return MNV_OK on success, error code otherwise.
 */
mnv_status_t mnv_run(mnv_ctx_t *ctx,
                     const mnv_act_t *input,
                     mnv_act_t       *output);

mnv_status_t mnv_run_with_model(mnv_ctx_t         *ctx,
                                const mnv_model_t *model,
                                const mnv_act_t   *input,
                                mnv_act_t         *output);

/* =========================================================================
 * SECURITY UTILITIES
 * ========================================================================= */

/**
 * @brief Re-verify model integrity without running inference.
 *
 * Useful for periodic integrity checks between inference calls.
 * Invalidates ctx->verified on failure.
 *
 * @param ctx    Initialized context.
 * @param model  Model descriptor.
 * @return MNV_OK if model is intact, MNV_ERR_TAMPER otherwise.
 */
mnv_status_t mnv_verify(mnv_ctx_t *ctx, const mnv_model_t *model);

/**
 * @brief Zero-wipe a memory region — guaranteed not optimized away.
 *
 * Uses volatile writes. Safe for wiping key material and activations.
 *
 * @param ptr   Pointer to memory region.
 * @param len   Number of bytes to zero.
 */
void mnv_secure_zero(void *ptr, size_t len);

/**
 * @brief Constant-time memory comparison.
 *
 * Returns 0 if equal, non-zero otherwise.
 * Execution time is independent of data values.
 *
 * @param a    First buffer.
 * @param b    Second buffer.
 * @param len  Length in bytes.
 * @return 0 if equal, non-zero if different.
 */
uint8_t mnv_ct_compare(const uint8_t *a, const uint8_t *b, size_t len);


/* =========================================================================
 * v1.1 — OUTPUT AUTHENTICATION
 * ========================================================================= */

/**
 * @brief Seed the PRNG used for LUT blinding.
 *
 * Call after mnv_init() with entropy from a hardware source:
 *   AVR:    free-running ADC noise
 *   STM32:  RNG peripheral
 *   Host:   /dev/urandom
 *
 * If not called, MNV_PRNG_SEED_DEFAULT is used (weaker — not recommended
 * for production deployments).
 *
 * @param ctx   Initialized context.
 * @param seed  32-bit entropy seed.
 */
void mnv_seed_prng(mnv_ctx_t *ctx, uint32_t seed);

/**
 * @brief Verify the output MAC produced by the last mnv_run_with_model() call.
 *
 * The MAC covers: output vector || input vector || a per-session counter.
 * This prevents replay of a previously valid inference result.
 *
 * @param ctx       Initialized context.
 * @param input     The input that was passed to mnv_run_with_model().
 * @param output    The output produced by mnv_run_with_model().
 * @return MNV_OK if MAC is valid, MNV_ERR_TAMPER otherwise.
 */
mnv_status_t mnv_verify_output_with_key(const mnv_ctx_t *ctx,
                                        const uint8_t   *device_key,
                                        const mnv_act_t *input,
                                        const mnv_act_t *output);

/**
 * @brief Get the raw output MAC bytes (8 bytes).
 *
 * Use this to transmit the MAC alongside the inference result to a
 * downstream consumer that can re-verify using mnv_verify_output().
 *
 * @param ctx  Initialized context.
 * @param mac  Output buffer, must be MNV_OUTPUT_MAC_SIZE bytes.
 */
void mnv_get_output_mac(const mnv_ctx_t *ctx, uint8_t *mac);

/* =========================================================================
 * DIAGNOSTICS (HOST TARGET ONLY)
 * ========================================================================= */

#if defined(MNV_TARGET_HOST)
/**
 * @brief Print context status to stdout. Host/debug only.
 */
void mnv_dump_status(const mnv_ctx_t *ctx);

/**
 * @brief Print weight statistics. Host/debug only.
 */
void mnv_dump_weights(const mnv_model_t *model, const mnv_ctx_t *ctx);
#endif

#ifdef __cplusplus
}
#endif

#endif /* MINERVA_H */
